#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config -d focused border_width 3
bspc config focused_border_color "#4286f4"

xrandr --output Virtual1 --mode 2560x1600
xrandr --dpi 155
xset r rate 200 30

setxkbmap -option caps:escape
vmware-user-suid-wrapper
feh --bg-center /home/rotaru_i/BackGround/bg1.jpg

polybar example&
